name: Build, test, deploy

on:
  workflow_dispatch:

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          npm install

      - name: npm run build
        run: |
          npm run build

      - name: npm run test
        run: |
          npm run test

      - name: cp -r build/* public/
        run: |
          cp -r build/* public

      - name: Publish to https://pan0.net
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
